# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: Issuer
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - name: Git Issue Creation
      uses: bryan-nice/git-issue-creation@1.1.1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_COMMIT_SHA: ${{ github.sha }}
          GITHUB_REPO_OWNER: 'dannyboy997'
          GITHUB_REPO_NAME: 'ogs-site'
          GITHUB_ISSUE_TITLE: 'Vote - PR ...'
          GITHUB_ISSUE_BODY: 'Vote by thumbs up or down on this issue'
